### ISSUE TITLE
Aries Agent: Exception: Timed out waiting for agent process to start 

### ISSUE THREAD

**Issue by johnburton9** [openwallet-foundation/acapy#1451]
Hi,
  I am going through the Aries Cloud Agent Python Demos.
  
  Using Windows 10, with the von-network successfully running in Docker on http://localhost:9000/

When I execute ./run_demo faber it registers the faber.agent and DID but then throws an exception. The following is the exception. Any thoughts/ideas? 
Shutting down agent ...
Faber      |
Faber      | Shutting down
Faber      | 2021-10-20 12:59:53,164 aries_cloudagent.commands.start ERROR Exception during startup:
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/commands/start.py", line 72, in init
Faber      |     await startup
Faber      |   File "/home/indy/aries_cloudagent/commands/start.py", line 28, in start_app
Faber      |     await conductor.setup()
Faber      |   File "/home/indy/aries_cloudagent/core/conductor.py", line 103, in setup
Faber      |     self.root_profile, self.setup_public_did and self.setup_public_did.did
Faber      |   File "/home/indy/aries_cloudagent/config/ledger.py", line 71, in ledger_config
Faber      |     async with ledger:
Faber      |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 276, in __aenter__
Faber      |     await self.pool.context_open()
Faber      |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 209, in context_open
Faber      |     await self.open()
Faber      |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 174, in open
Faber      |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
Faber      |     open_pool_ledger.cb)
Faber      | concurrent.futures._base.CancelledError
Faber      | 2021-10-20 12:59:53,166 asyncio ERROR Task exception was never retrieved
Faber      | future: <Task finished coro=<run_loop.<locals>.done() done, defined at /home/indy/aries_cloudagent/commands/start.py:77> exception=Runtim
eError('cannot reuse already awaited coroutine',)>
Faber      | RuntimeError: cannot reuse already awaited coroutine
Faber      | Exited with return code 0
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/demo/runners/faber.py", line 759, in <module>
    asyncio.get_event_loop().run_until_complete(main(args))
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/home/indy/demo/runners/faber.py", line 413, in main
    schema_attrs=faber_schema_attrs,
  File "/home/indy/demo/runners/agent_container.py", line 655, in initialize
    await self.agent.start_process()
  File "/home/indy/demo/runners/support/agent.py", line 607, in start_process
    await self.detect_process()
  File "/home/indy/demo/runners/support/agent.py", line 917, in detect_process
    + f"Admin URL: {status_url}"
Exception: Timed out waiting for agent process to start (status=None). Admin URL: http://127.0.0.1:8021/status

**Comment by ianco** [comment]
The agent is not able to connect to the ledger, and is timing out.

You can try this command which will connect to a public ledger:  `LEDGER_URL=http://test.bcovrin.vonx.io ./run_demo faber`

**Comment by aipirvu** [comment]
@ianco is right:
> This IP should match the IP in the genesis file at http://localhost:9000/genesis

I had the same issue on windows 10 with docker running on WSL2. The host ip address that is determined by the scripts is not correct. I had to run `export DOCKERHOST=[HOST_IP]` to make the `DOCKERHOST` variable already available to the scripts so they don't attempt to determine it by themselves.
