### ISSUE TITLE
Proof presentation with constraint filters not working as expected

### ISSUE THREAD

**Issue by acuderman** [openwallet-foundation/acapy#1457]
## Integer number
I tested number constraints inside the proof requests and It doesn't work as expected. In the process the verifier agent throws an error: 
```
aries_cloudagent.protocols.present_proof.dif.pres_exch_handler.DIFPresExchError: Constraint specified for citizenship_input_1 does not apply to the enclosed credential in $.verifiableCredential[0]
```
The problem is that the expected [credential value type in the proof presentation is number](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/protocols/present_proof/dif/pres_exch_handler.py#L753), but in reality, It is an object:
```
{
    "type": "xsd:integer",
    "@value": "10"
}
```

### Reproduction steps:
- Add `"lprNumber": 10` property to [credentialSubject object](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/runners/faber.py#L150)
- Change path of first field contraint in the [proof request](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/runners/faber.py#L342) to ` "path":["$.credentialSubject.lprNumber"]`
- Set as filter:
```
 "filter": {
    "minimum": 3,
    "type": "number",
}
```

- Run Alice and Faber
```
./run_demo faber --did-exchange --cred-type json-ld --wallet-type askar
./run_demo alice --wallet-type askar
```
- Issue credential and create proof request
- Observe the issue

## Float number
There is another issue with float numbers. It is different than the integer issue because the holder can not even create a proof presentation. Error:

```
 TypeError: must be real number, not str
```

### Reproduction steps:
- Add `"lprNumber": 10.2` property to credentialSubject object
- Everything else same as reproducing Integer issue

## Value Range
Range constraints are not supported since [else if is used instead of ifs](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/protocols/present_proof/dif/pres_exch_handler.py#L711)
An example use case of range validation is that the user needs to be between 18 and 21 years old. Can we allow range predicates?

**Comment by shaangill025** [comment]
1. Regarding **Integer number** issue, this should be fixed in PR#1430.

2. Regarding **Float number ** issue, this error (`must be real number, not str`) is triggered when deriving the credential. I tested the `reveal_doc` in JSON-Playground and it seems to be correct. I will raise an issue regarding this.  

3. > Regarding range validation. It works if we specify the same paths multiple times with a different filter. Is that the intended use?

This is the intended use. From your use case, so as to ensure that `age` is between 18 and 21, you will need to specify 2 `fields` on the same `path, ["$.credentialSubject.age]` with `minimum filter as 18` and `maximum filter as 21` respectively.

4. `oneOf` filter has been implemented in PR#1430 and it follows this structure (list of lists):
```
"schema": {
 "oneOf":[
    [
      {
          "uri": "https://example.com/passport#passport"
      }
    ],
    [
      {
          "uri": "https://example.com/drivers-license#drivers-license"
      },
      {
          "uri": "https://www.w3.org/2018/credentials#VerifiableCredential"
      }
    ]
]
```

**Comment by acuderman** [comment]
Thanks, this sounds good. Yes Ideally all credentials that match one of the schemas would be returned, so that the holder has the ability to decide which one to use (the order should not matter).

What about the issue I described [here](https://github.com/hyperledger/aries-cloudagent-python/issues/1457#issuecomment-952864881). Is the validation that the credential's schema in proof presentation matches the schema defined in the proof request also added on the verifier side also by PR #1430?

**Comment by shaangill025** [comment]
> What about the issue I described [here](https://github.com/hyperledger/aries-cloudagent-python/issues/1457#issuecomment-952864881). Is the validation that the credential's schema in proof presentation matches the schema defined in the proof request on the verifier side also added by PR #1430?

I wasn't able to replicate this issue, schema filtering is working as expected. For me with `"uri": "https://w3id.org/test#test"` the presentation includes no credential.

**Comment by acuderman** [comment]
That's true, but if Aca-py is slightly modified on the holder side, in order to send the credential inside proof presentation even though schema doesn't match. The validator agent will not notice that. We cant assume that all agents will be harmless.

I prepared an example: https://github.com/acuderman/aries-cloudagent-python/pull/3/files

When the demo is run (Alice and Faber), the proof is still valid even thought It shouldn't be since schemas don't match.

**Comment by shaangill025** [comment]
> That's true, but if Aca-py is slightly modified on the holder side, in order to send the credential inside proof presentation even though schema doesn't match. The validator agent will not notice that. We cant assume that all agents will be harmless.

This should be addressed now in PR #1430.

**Comment by acuderman** [comment]
@shaangill025 Thanks! Went through the cases and looks good.

Would It also make sense that a problem report is created in case that the Verifier throws: `DIFPresExchError`?

**Comment by vidp1** [comment]
> 2\. Regarding **Float number ** issue, this error (`must be real number, not str`) is triggered when deriving the credential. I tested the `reveal_doc` in JSON-Playground and it seems to be correct. I will raise an issue regarding this.

Hello @shaangill025, 

was this issue raised? If yes could you please provide the issue number, so we can track it.

Thank you!
