### ISSUE TITLE
`--base-wallet-routes` flag no longer works

### ISSUE THREAD

**Issue by dbluhm** [openwallet-foundation/acapy#3283]
After the swap to using decorators to delineate routes accessible by tenants and routes accessible by admins, the ability to grant access to the base wallet to additional routes was lost.

This option made it possible for a base wallet to form a didcomm connection with a mediator and then use that as a base mediator for all tenants, among other things.

cc @esune @jamshale

**Comment by dbluhm** [comment]
Yeah, indeed, I only just detected this myself.

**Comment by esune** [comment]
I didn't even know this setting/option existed 😅. My understanding was that the base wallet would always ONLY deal with tenant provisioning tasks and nothing else, so the decorators were set-up to function this way.

That being said, I think we would have to move [this logic](https://github.com/openwallet-foundation/acapy/blob/15eb009192edfc3b60f1028e5b44d708e203aada/acapy_agent/admin/server.py#L262-L282) into the [tenant_authentication](https://github.com/openwallet-foundation/acapy/blob/15eb009192edfc3b60f1028e5b44d708e203aada/acapy_agent/admin/decorators/auth.py#L44) decorator for things to work.

Adding a separate decorator just for this would be also an option and it would be more explicit, however the fact that we'd have to basically blanket apply it everywhere AND, more importantly, the added complexity of having multiple decorators stacked (in the right order) makes me think it is actually not the best option.

**Comment by esune** [comment]
Taking a stab at this since it was brought up at today's maintainers meeting
