### ISSUE TITLE
"No endorser invitation, can't connect automatically." message on startup even when the agent instance is connected to an endorser service

### ISSUE THREAD

**Issue by WadeBarnes** [openwallet-foundation/acapy#3308]
## Observed behavior:
When upgrading an agent instance (`0.10.2` to `0.12.2`) in this case I started seeing the following message:
```
2024-10-23 13:10:34,142 aries_cloudagent.utils.endorsement_setup INFO No endorser invitation, can't connect automatically.
```
The agent in question was already connected to an endorser service and the connection was know to be working.

## Expected behavior:
To not see this message when an agent already has a working connection established with as endorser service.
This message should also not be displayed if (these scenarios were not tested):
- The agent is not configured to use an endorser service; i.e. endorser functionality is disabled.
- The agent is configured as an Endorser.

## Steps to reproduce:
- Using an existing agent instance (`0.10.2` for example) that is already connected to an endorser service.
- Set the log level to `INFO`.
- Upgrade the instance to a newer version of aca-py, `v0.12.2` for example.
- "No endorser invitation, can't connect automatically." log message appears.

This issue is not restricted to upgrades.  The same issue will occur if you setup a new agent instance with an endorser connection.

**Comment by jamshale** [comment]
I think i screwed this up :/

But, I'm pretty sure the error message is misleading. The previous endorser connection should still exist and work correctly.

**Comment by WadeBarnes** [comment]
You are connect, from what I can tell the existing endorser connection is not affected and still works, it's existence is just not being taken into account.
