### ISSUE TITLE
Sonarcloud main scan for new code not happy

### ISSUE THREAD

**Issue by jamshale** [openwallet-foundation/acapy#3383]
Ever since we moved to OWF when code is merged to main it's been reporting wrong for new code. Reports 0 code coverage and lots of hotspots. I don't know why, but it makes the badges in the README look bad and repots an X when there's nothing actually long. 

Should look at repairing it and adjusting some security hotspot rules that don't apply to the project. This likely requires getting Ry Jones of OWF organization to give some admin rights in sonarcloud to a regular maintainer.

**Comment by swcurran** [comment]
@ryjones — can you please help with this one?  Something different between the Hyperledger settings we had and OWF.

Thanks!

**Comment by ryjones** [comment]
You both should have the ability to manage it now

**Comment by swcurran** [comment]
@jamshale — can you update the configuration, please?  Way beyond me :-)

**Comment by jamshale** [comment]
This seems to be fixed now. Will close and keep an eye on it.
