### ISSUE TITLE
Multitenancy credential storage

### ISSUE THREAD

**Issue by PatStLouis** [openwallet-foundation/acapy#3387]
I noticed that when storing/querying credentials stored in a multi-tenant agent, the credentials are shared across sub wallets. I would like to understand why I get this behavior and how we can address this as this seems less than ideal.

**Comment by PatStLouis** [comment]
I'm calling the `/vc/credentials/store` endpoint, which invokes the vcHolder:
https://github.com/openwallet-foundation/acapy/blob/6ddb592c9929be4a76b329aeaeb874b76316ee24/acapy_agent/vc/vc_ld/manager.py#L405

**Comment by PatStLouis** [comment]
This is similar to how the issue-credential-v2 ld_proof filter stores the credential:
https://github.com/openwallet-foundation/acapy/blob/6ddb592c9929be4a76b329aeaeb874b76316ee24/acapy_agent/protocols/issue_credential/v2_0/formats/ld_proof/handler.py#L367

**Comment by jamshale** [comment]
I think there might be a few places multitenancy holders might have issues. It's not a scenario I look at often or gets tested that much. 

I haven't tested it yet but I was looking at anoncreds cred storage and the multitenancy stuff looked a little odd.

I'll try and have a look today.

**Comment by dbluhm** [comment]
This was introduced in #3010 and was included in 1.0.0 and onward; a backport was also committed to 0.11.x and 0.12.x :man_facepalming:

@swcurran sorry :grimacing: this will mean a new LTS patch release for those releases

**Comment by swcurran** [comment]
OK…that will be fun.  I’d be tempted to not do 0.11.x since it’s LTS runs out in January 2025, but doing one or both does not make a big difference in effort.
