### ISSUE TITLE
Create PRs on LTS 0.11.x and 0.12.x branches for PR 3391

### ISSUE THREAD

**Issue by swcurran** [openwallet-foundation/acapy#3394]
PR 3391 needs to be backported to 0.11.x and 0.12.x branches.

Please create the PRs for those branches, so that we can generate LTS releases.

**Comment by swcurran** [comment]
Volunteers for this amongst the @openwallet-foundation/acapy-admins ?

**Comment by jamshale** [comment]
I can look into this. The trickiest part will be the token to upload to `aries_cloundagent` I'm not sure if the token got moved of will still work and don't have any admin rights on that pypi project. 

I'll see if I run into any problems with it. All the required github actions will need the repo names changed as well in the PR.

**Comment by dbluhm** [comment]
@jamshale my recommendation is to only carry over the `ClassProvider.Inject(Profile)` line and that's it for 0.11.x and 0.12.x. The other Open API changes won't impact functionality of those releases.

**Comment by swcurran** [comment]
Completed and released.
